# This is a basic workflow to help you get started with Actions

name: Validate Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkCode:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: NPM Install
      run: npm Install

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm run test
