name: Validate PR

on: 
  pull_request:
    branches: [master]

jobs:
  runLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: NPM Install
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm run test